# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ self, inputs, ...}: {
flake.nixosModules.serverHardware = { config, lib, pkgs, modulesPath, ... }:

	{
	# GOES HERE

	};

}
